// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"
#include <sstream>
#include <climits>

//----------------------------------------------------------
// Helper: temporarily redirect cin from a string for one scope.
//----------------------------------------------------------
struct CinRedirect {
    std::streambuf *old;
    std::istringstream iss;
    CinRedirect(const std::string &s) : iss(s) {
        old = std::cin.rdbuf(iss.rdbuf());
    }
    ~CinRedirect() { std::cin.rdbuf(old); std::cin.clear(); }
};

//==========================================================
// [T1] getTwoValues — re-prompt until val1 < val2
//==========================================================
TEST_CASE("T1a: normal input 10 20 accepted", "[T1]") {
    CinRedirect c("10 20\n");
    int a = 0, b = 0;
    getTwoValues(a, b);
    REQUIRE(a == 10);
    REQUIRE(b == 20);
}

TEST_CASE("T1b: reject 20 10 then accept 10 20", "[T1]") {
    CinRedirect c("20 10\n10 20\n");
    int a = 0, b = 0;
    getTwoValues(a, b);
    REQUIRE(a == 10);
    REQUIRE(b == 20);
}

TEST_CASE("T1c: reject equal 5 5 then accept 5 10", "[T1]") {
    CinRedirect c("5 5\n5 10\n");
    int a = 0, b = 0;
    getTwoValues(a, b);
    REQUIRE(a == 5);
    REQUIRE(b == 10);
}

//==========================================================
// [T2] getNextPrime — smallest prime strictly greater than begin
//==========================================================
TEST_CASE("T2a: getNextPrime(10) == 11", "[T2]") {
    REQUIRE(getNextPrime(10) == 11);
}

TEST_CASE("T2b: getNextPrime(1) == 2 (boundary, smallest prime)", "[T2]") {
    REQUIRE(getNextPrime(1) == 2);
}

TEST_CASE("T2c: getNextPrime(13) == 17 (already prime -> strictly greater)", "[T2]") {
    REQUIRE(getNextPrime(13) == 17);
}

TEST_CASE("T2d: getNextPrime(100) == 101", "[T2]") {
    REQUIRE(getNextPrime(100) == 101);
}

TEST_CASE("T2e: getNextPrime(200) == 211", "[T2]") {
    REQUIRE(getNextPrime(200) == 211);
}

//==========================================================
// [T3] getPrevPrime — largest prime strictly less than end
//==========================================================
TEST_CASE("T3a: getPrevPrime(20) == 19", "[T3]") {
    REQUIRE(getPrevPrime(20) == 19);
}

TEST_CASE("T3b: getPrevPrime(100) == 97", "[T3]") {
    REQUIRE(getPrevPrime(100) == 97);
}

TEST_CASE("T3c: getPrevPrime(13) == 11 (already prime -> strictly less)", "[T3]") {
    REQUIRE(getPrevPrime(13) == 11);
}

TEST_CASE("T3d: getPrevPrime(3) == 2 (boundary, smallest prime)", "[T3]") {
    REQUIRE(getPrevPrime(3) == 2);
}

TEST_CASE("T3e: getPrevPrime(250) == 241", "[T3]") {
    REQUIRE(getPrevPrime(250) == 241);
}

//==========================================================
// [T4] Integration — isPrime + combined prev/next ranges
//==========================================================
TEST_CASE("T4a: isPrime basic correctness", "[T4]") {
    REQUIRE(isPrime(2) == 1);
    REQUIRE(isPrime(3) == 1);
    REQUIRE(isPrime(4) == 0);
    REQUIRE(isPrime(17) == 1);
    REQUIRE(isPrime(25) == 0);
    REQUIRE(isPrime(1) == 0);
}

TEST_CASE("T4b: range 50-60 -> next=53, prev=59", "[T4]") {
    REQUIRE(getNextPrime(50) == 53);
    REQUIRE(getPrevPrime(60) == 59);
}

TEST_CASE("T4c: range 1350-1360 -> next=1361, prev=1327", "[T4]") {
    REQUIRE(getNextPrime(1350) == 1361);
    REQUIRE(getPrevPrime(1360) == 1327);
}
